services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - APP_ENV=${APP_ENV}
      - CHANNEL_ID_UA=${CHANNEL_ID_UA}
      - CHANNEL_ID_TR=${CHANNEL_ID_TR}
      - CHANNEL_ID_IL=${CHANNEL_ID_IL}
      - CHANNEL_ID_RU=${CHANNEL_ID_RU}
      - CHANNEL_ID_IR=${CHANNEL_ID_IR}
    volumes:
      - ./titles:/app/titles
